### ISSUE TITLE
End-to-end testing Single Page Apps and APIs with Cucumber.js & Puppeteer

### ISSUE THREAD

**Issue by paulbjensen** [lnug/speakers#125]
Developing web applications as separate front end and back end parts is a common practice, but brings with it the challenge of how to test those parts together in an end-to-end fashion.

In this talk, I will show you a strategy for being able to test your web application with Cucumber.js and Puppeteer, a library for running Google Chrome in headless mode. We'll also explore how to handle things like seeding the database for the API before running tests, how to select elements in the DOM via Cucumber step definitions, and how to do this in a nice fashion using Node 8's async/await feature. 

My name is Paul Jensen, I'm the author of Manning's Cross Platform Desktop Applications, and I'm the Lead Innovation Engineer at Starcount. My twitter handle is paulbjensen.

**Comment by admataz** [comment]
Hi @paulbjensen  - great to have you back - and thanks for the talk proposal. I've always liked Cucumber, for getting clarity on features. I think it will be great to hear your approach here...  and particularly how node developers can use cucumber.js - will you cover anything on best approaches/options for setting up test-runners? I used cucumber with webdriver.io on a job - would be interested to hear how you set things up too. 

You know the drill because you've done this before, but members have asked us to formalise the agreement with speakers a little: 

So just checking: 
- [ ] Length of talk - needs to be 20-25 mins.
- [ ] Code of Conduct - as part of our community we need to make sure all speakers agree with that - see https://lnug.org/code-of-conduct.html

@lnug/organisers  - any thoughts/seconders on this proposal? 

Dates: We are working out our upcoming schedules for 2018 - I can guarantee an available slots April 25th, May 23rd and June 27th - and possibly February 28th and March 28th (I'm needing to confirm some details) 

Any preferences - considering your other talk proposal too - may be good to spread them out?

**Comment by jkbits1** [comment]
@admataz @paulbjensen I've used a different setup for functional testing recently, so very interested to see how these choices compare. Seconded 👍 😄

**Comment by paulbjensen** [comment]
Hi,

Thanks. I agree to the talk length and the code of conduct. I will make sure to cover the bits about Cucumber practices and options (e.g. how to DRY to steps in Cucumber files), and cover how to use alternative options to Puppeteer (for testing browsers other than Chrome).

As for schedule, I'm flexible to slot options.

**Comment by admataz** [comment]
Thanks @paulbjensen  - I've put you in for April 25th   - I hope that still suits?

**Comment by paulbjensen** [comment]
That’s fine by me.

**Comment by admataz** [comment]
Hi @paulbjensen 

Just confirming you're all good for Wednesday?

**Note we are not at Makers this month!!**

The venue is:
Conde Nast
Adelphi Building, 1-10 John Adam St Level 9 · London
The nearest Tube stations are Embankment and Charing Cross

I will be there from about 6pm to get things set up - your name will be at security. If you arrive before me please ask for Michelle Garret. 

See you there!

**Comment by paulbjensen** [comment]
yes

**Comment by admataz** [comment]
Hi @paulbjensen  - thanks again for your talk last week - lots of good feedback. I hope you had a good evening. Please let me know if you have any feedback from the speaker perspective...

I've just uploaded the videos from the night - you can find them here: https://www.youtube.com/playlist?list=PLam_80-FY3vTu3eOUOavEepvDLHVAy_sZ

**Comment by paulbjensen** [comment]
Thanks @admataz, yeah it was a great night, I look forward to the next one.

On that note, I see there's only 1 talk lined up so far for this month's event. Is there another talk on the cards that's not in this repo?

**Comment by admataz** [comment]
Hi @paulbjensen  - yes - there is still a slot available - I'm putting out word

**Comment by paulbjensen** [comment]
Cool.

If no one else comes up with a proposal in time, I am willing to provide a backup proposal to potentially fill that slot.

**Comment by admataz** [comment]
thanks - that would be awesome

**Comment by paulbjensen** [comment]
Cool. I will drum up some proposals. If they're good and no one comes forward with a proposal for this month, we can slot one in.

**Comment by paulbjensen** [comment]
Added a proposal https://github.com/lnug/speakers/issues/137
