### ISSUE TITLE
Managing cloud resources in a distributed and fault-tolerant manner with EVRYTHNG’s resource manager

### ISSUE THREAD

**Issue by stephendeyoung** [lnug/speakers#138]
At [EVRYTHNG](http://evrythng.com/) we had to a build a number of Node.js applications that required managing multiple resources in a distributed environment. For example, handling real-time connections to other clouds such as Nest and Honeywell and sending notifications to [IFTTT](https://ifttt.com/) applets. What if there was a library that handled the allocation and distribution of these resources so developers could focus on the core business logic of their application?

The EVRYTHNG distributed resource manager is a Node.js library that solves this problem. Developers don’t need to worry about maintaining real-time connections when new nodes are added to the system or if one of them goes down.

In this talk I would demonstrate the resource manager so attendees will see what problems it solves for us at EVRYTHNG. In addition, they will gain an understanding of how we use Node.js at our company and how it helps us scale. Please note that this library is not currently open source but it should be in the next 1-2 months.

I work as a Technical Lead for EVRYTHNG who provide an IoT platform for businesses around the world. It’s my role to decide on the architecture for various parts of the platform and how we will build these components using Node.js. I’ve been programming in Node for five years.

**Comment by admataz** [comment]
Hi @stephendeyoung  - thank you for your talk proposal  - this is  great - I'd love to hear more on this kind of use of node - and it will be nice to see how EVRYTHNG has progressed since @domguinard's talk at LNUG a couple year's ago ([Node.js, the Web and the IoT](https://github.com/lnug/speakers/issues/80). 

We are currently working out our final schedule for this month's meetup (next week Wednesday 23rd May). There may still be a speaker slot available. Does that work for you - if not, there's June/July/Aug... (if you want to wait till your library is ready and open source?)

Let me know.

meanwhile... 
 some members have asked us to formalise the agreement with speakers: 
So just checking - and can you confirm: 
- [ ] Length of talk - needs to be 20-25 mins.
- [ ] Code of Conduct - as part of our community we need to make sure all speakers agree with that - see https://lnug.org/code-of-conduct.html

@lnug/contributors  - can I get another seconder for this talk please?

**Comment by admataz** [comment]
Hi @stephendeyoung  - I've moved you to June  - how does that suit?

**Comment by stephendeyoung** [comment]
@paulbjensen thanks mate!

@admataz June works for me. Length of talk is fine and I agree to the Code of Conduct.

**Comment by admataz** [comment]
Great stuff - you are in for June! Come along next week and say hi if you can

**Comment by admataz** [comment]
Hi @stephendeyoung  - just confirming you're all good and ready for your talk at this Wednesday's LNUG meetup? 

I'll be at the venue from about 6pm to get things set up. Doors open to attendees  at 6:30pm and we usually get started with talks around 7pm...  

Will be good if you can get there sometime before 6:30 just so we can test the projector and video.  Let me know if you need anything special.

Details:
Venue: 
CONDÉ NAST
ADELPHI
1-11 JOHN ADAM ST
WC2N 6HT

Your name will be on the door with security. 

If you need to contact me - my number is 07757 234443

**Comment by stephendeyoung** [comment]
@admataz Yes I'm all good for Wednesday. 

Thanks for the details. I'll get there around 6.15 I think.

**Comment by admataz** [comment]
Hey @stephendeyoung  - Thanks again for a great talk on Wednesday - overall it was a good night for all... I hope you enjoyed it. If you have any feedback from the speakers perspective - please let me know!

I'll post the link to the video of your talk here when it's ready

Hopefully see you again at another LNUG meetup soon!

**Comment by stephendeyoung** [comment]
@admataz Thanks for the feedback and thanks for organising the meetup. I thought it all went very smoothly.

Is it possible to get any more detailed feedback on my talk at all either from you or other audience members? I would like to know how I can get better.

**Comment by admataz** [comment]
Hey @stephendeyoung  - I've at last uploaded the videos: 
https://www.youtube.com/playlist?list=PLam_80-FY3vQZKP5F_O2Bo4A8mQqyvh_J

If you want you can share the link and invite feedback via twitter or on the meetup page?  (mention @lnugorg and I'll make sure to retweet)

I'll be away the next couple meetups - so hopefully see you again after September!

**Comment by stephendeyoung** [comment]
Thanks very much @admataz
