### ISSUE TITLE
Let's dip our toes in es6

### ISSUE THREAD

**Issue by errietta** [lnug/speakers#142]
A beginner's overview of new features in ES6. This talk goes through some of the newly introduced features in es6 with live coding examples.

We'll go over some of the features, for example:
* Rest/spread
* Destructuring
* Arrow functions
* Object literals
* Constants

I confirm my talk is 20 mins long in total.
I confirm that I will abide by the Code of Conduct

**Comment by errietta** [comment]
I appreciate most people know this stuff, but there are always beginners, or people who have experience in es5 but not es6, and talks like that could help get new people in.

**Comment by admataz** [comment]
Hi @errietta! Thanks so much for your talk proposal...  

I agree that there is a place for a 'beginners' talk subject at LNUG  - and I'd support more of this (we've had a few over the years and they have been well received). Here are a few thoughts/ideas from me - and maybe these can help you shape the talk into something that can be appropriate for LNUG and make a really good talk.  

- focus on relevance of es6 - how did adopting es6 features make a difference to your work as a developer? What coding problems were better solved?  what magic did features like rest/spread, etc enable you to achieve? also what is the relevance of es6 features **to the context of node.js** development and other parts of the js developer ecosystem?
- tell a story rather than a provide a feature tour or a tutorial -  a narrative that your audience will enjoy. Something of personal perspective/experience (maybe tied to the point above) or a more general narrative arc will go a long way to making the talk 
- it's fine to have a talk aimed at introductory material, but remember that a good proportion of the audience are experienced developers, maybe worth at least a nod to this part of the audience and mention some advanced aspects to your topic  - the potential and possibility of other new features of JS in es6 (async/await, generators, promises, etc) and beyond (es2017+) and the continuing development of the language and its future. 

These are just some ideas - please let me know what you think... 

(@lnug/contributors and @lnug/organisers  - feel free to add your thoughts/feedback too)

**Comment by errietta** [comment]
@admataz thanks for the advice! I'm a bit cautious of going into depth with advanced features due to the 20 minute limit. Maybe I could instead speak about specific features like promises instead of talking about new es6 features in general, then it would be easier to fit in? What do you think!

**Comment by d4nyll** [comment]
My $0.02.

I agree with the feedback that's already been given - I also feel that a generic tour of ES6 would be too 'easy' and generic. For beginners, these are also the things they can find with a simple Google search.

If you are looking to do a talk about promises, I'd like to share a format that has worked really well before in my previous company.

The talk was about _quirks_ and _common mistakes_ of using promises. The presenter prepared some code that uses promises, and asks the audience to vote on what they expect the outcome of the execution would be. And many of us would get it wrong and the presenter would explain why.

For instance:

```
function retA() { return Promise.resolve('A') }
function retB() { return Promise.resolve('B') }
function test() {
  const promise = retA();
  promise.then(() => retB())
  return promise;
}
test().then(console.log)
```

Some will expect the console to log `'A'`, whilst other will expect `'B'`.

Whilst audience participation may not be the right approach, having a talk on quirks and common mistakes it more likely to keep within the time limit, keep the audience engaged, and it's also more likely to be applicable to a wider audience.

**Comment by admataz** [comment]
hi @errietta 
yes - I see your point about going in to depth - it's impossible to do the features justice in 20 minutes. (we can stretch to 25 if necessary, but still). 

So I would suggest if you want to keep the talk subject accessible and at an intro-level  - then consider the approaches I mentioned (how es6 features helped solve a specific coding problem for you  and a story/perspective/narrative)  - this will make an entertaining talk to all levels. Newbies will appreciate the learning - and those of us with experience always enjoy these stories, because if we don't at least learn something technically new - we've all been there and can relate - and sharing these experiences is a major part of what a meetup is about!

I look forward to any ideas you put forward - and happy to discuss at any point if you want to take this offline to develop the idea before posting. 

(thanks @d4nyll and @FabioAntunes too for input)

**Comment by orliesaurus** [comment]
Hello hello! Any updates on this one? Is this been still worked on? I am asking as we're looking who to put forward to be in the August speakers line-up :)

**Comment by errietta** [comment]
Definitely want to do something, sorry, got busy and forgot 😊 
I had this issue that the talk I wanted to do is probably too basic for most people here.. So still need to think about what I can do that is more interesting 🤔 
Maybe not this month though 😢

**Comment by orliesaurus** [comment]
Alright thx @errietta - keep us posted !

**Comment by admataz** [comment]
Hi @errietta  - have you had any further thoughts/ work/ on this talk?

**Comment by errietta** [comment]
@admataz no, but I have an idea for a more interesting subject which is about deploying node apps with serverless and cloudformation, can I do that instead? Should I raise another issue? 😄

**Comment by admataz** [comment]
Thanks @errietta  - yes please raise another issue with a new talk abstract. And you can close this one if it's no longer relevant.

On the topic of cloud deployments - we have a couple upcoming talks on the topic scheduled for October - see https://github.com/lnug/speakers/milestone/43 - if you could come up with something that complements these  - and doesn't overlap too much - that would be great!

**Comment by errietta** [comment]
@admataz cheers! 
https://github.com/lnug/speakers/issues/153

Hopefully I can get this one in 🤞
