### ISSUE TITLE
TypeScript: It's time to migrate!

### ISSUE THREAD

**Issue by Talento90** [lnug/speakers#159]
TypeScript adoption it's been a reality in the last years. This presentation is going to be a demonstration on how we can take advantage of the TypeScript compiler to have a smooth migration from JavaScript to TypeScript.

I am Marco, Software Engineer that believes software must be simple, intuitive and reliable. Currently working at Beamery. https://twitter.com/Talento90

**Comment by admataz** [comment]
Hi @Talento90  - thanks for your talk proposal! Sorry it's taken me a while to respond...

Wow, this is a tough topic  - you are brave to take it on - but yes - we're probably overdue a types/typescript talk - we had a one [a few years ago](https://github.com/lnug/speakers/issues/35) - but I guess things have come a way since then...

To keep it on topic four our group -  I'd be interested to hear what you have to say about typescript specifically for server side node.js developers - as well maybe cli tool and library developers writing with node.js.  - i.e. there a lot of talks and articles out there that give generic reasons, or approaches to TS for react and client-side js developers - it would be good to focus on the node.js use case and the advantages you see there. 

I know a few node devs who really don't like typescript as they feel it is limiting and pointless - tests and validation are fine as far as they are concerned - and the added abstraction of another layer of compilation and new verbose syntax to their node is not helpful, and gets in the way of writing js the way they feel comfortable. Can we get a deeper look into the compiler and ways to write js that help these kinds of people?  Or is it just not for everyone?

I get that you are proposing a _how_ rather than _why_ talk - and I also value the fact that there will be opinions. But will you be able to illustrate `how we can take advantage of the TypeScript compiler` in a convincing way?  I really don't want a run-down of the features of type system and how great they are in theory for your safety and IDE - I'd really like to see some node code moved from JS to TS in a way that clearly illustrates the advantages. Can you do it?

How are you for 27th  February or 27th March  ?

And a couple small things we need to confirm

- [ ] Length of talk - needs to be 20-25 mins 
- [ ] Code of Conduct - as part of our community we need to make sure all speakers agree with that - see https://lnug.org/code-of-conduct.html

**Comment by Talento90** [comment]
Hello @admataz - First of all, thanks for your answer! 

To be honest, most of my experience using TypeScript it is been on the backend side with node.js. Nowadays, TypeScript it’s been a sensitive topic in the community but my goal is not to show the advantages of having types, as you have mentioned there are plenty of tutorials on the internet explaining that. 

What I want to show, is how we can take advantage of the TypeScript compiler to provide a better development experience (refactoring, updating libraries), even just using javascript. At the end I will show how we can convert an API written in JS to TypeScript.

27th February would be great!

I agree with the code of conduct and that I will talk 20-25 minutes.

**Comment by admataz** [comment]
Sounds good You're on for 27th Feb!

**Comment by admataz** [comment]
Hi @Talento90  - it's today! 

Just confirming - How are things looking for your talk? All good?

details of the venue: 
```
CONDÉ NAST
ADELPHI BUILDING
1-11 JOHN ADAM ST
WC2N 6HT
```

I will be there from about 6:15pm getting a few things set up - people start arriving around 6:30 and we plan to start with talks after a brief intro and welcome at 7pm

If you have any issues - please call me: 07757234443

See you there!

**Comment by Talento90** [comment]
Hello @admataz, Everything is fine thank you! About today, yes confirm!

See you around 6:15 👍

**Comment by admataz** [comment]
Hey @Talento90 -  Thanks so much for your talk at LNUG the other week - I think people really appreciated the introduction to Typescript and seeing the possibilities... 

The video of your talk is now available online: 
https://www.youtube.com/watch?v=qPLVn2Ft3vw&list=PLam_80-FY3vSjatQNzSPQhBAb_hrSlWJk&index=3

If you have any feedback around the event or organisation - please let us know!

Hopefully see you again at LNUG soon!
