### ISSUE TITLE
How to build an advanced Admin Panel in Node.js and React using AdminBro

### ISSUE THREAD

**Issue by malgorzatagalinska** [lnug/speakers#168]
[How to build an advanced Admin Panel in Node.js and React using AdminBro]

[Wojciech Krysiak, CTO in Software Brothers - software house specialized in building usable web and mobile applications for international Clients. Wojciech loves coding using the latest technologies: WebGL, HTML5, RoR, prediction.io, meteorjs and many more. He also supports his clients in IT, UX and Business Models.]

**Comment by admataz** [comment]
hi, thanks for your talk proposal. A couple of points about talks at LNUG: 

- your talk description doesn't really tell us much of what your intending to talk about - so there's not much to go on here
- we tend to discourage product walk-throughs/promotions - rather than how to use your product,  it would be better to hear about how you built it
-  our community would much prefer to hear about the challenges/ innovations/ insights you have had with node.js and associated technologies in building your project - and how this knowledge that you are sharing is interesting to us all. 

I'd advise you to have a look at some of the previous issues in this repos to see how we shape them to help make interesting talks - you need to at least provide a decent description - and with some idea of the audience and their interests. 

Your AdminBro product looks great and we do invite developers to share their open source projects at meetups with a quick 5 minute lightning talk - if you think this is more appropriate for you, instead of a featured talk let us know and we'll plan around that instead. 

this is my opinion - @lnug/organisers @lnug/contributors  - please add your thoughts here

**Comment by admataz** [comment]
Hi I spoke with Wojciech at our meetup - was great to meet. - I think he has a good idea of how to pitch the talk for next time - please create a new issue when you're next back in town!

**Comment by malgorzatagalinska** [comment]
Sure:) I will arrange it!
We will figure out a nice topic - but maybe you have some suggestions for
us?

And I hope next time we'll meet in person:)!


Kind Regards / Pozdrawiam
Małgorzata Galińska
Communication Manager

Software Brothers sp. z o.o.

malgorzata.galinska@softwarebrothers.co
*www.softwarebrothers.co/ <http://www.softwarebrothers.co/>*
Facebook <https://www.facebook.com/softwarebrothers/>

*Head Office:*
Software Brothers
Raclawicka Center
Skarbowcow 23b
53-025 Wroclaw, Poland

This message contains confidential information and is intended only for the
individual named.
If you are not the named addressee you should not disseminate, distribute
or copy this e-mail.

Copyright 2019 © Software Brothers sp. z o.o.
ᐧ


ᐧ

czw., 4 lip 2019 o 12:44 Adam Davis <notifications@github.com> napisał(a):
