### ISSUE TITLE
Writing and publishing ES6 code today

### ISSUE THREAD

**Issue by jamesallardice** [lnug/speakers#28]
On February 20th the first release candidate of the 6th edition of the ECMAScript specification (ECMAScript 2015 as it is now officially known) was released. The language is rapidly stabilising and the new features are slowly but surely making their way into the existing JavaScript engines. Unfortunately, it will still be a while before we're able to write ES6 code and have it run natively in either browsers or Node and io.js. Thankfully TC39 (the group responsible for the development of the ECMAScript specification) put a lot of effort into ensuring backwards compatibility so it is possible to use a large and growing proportion of ES6 today.

This talk will look into some of the technologies and techniques that can be used to write, publish and deploy ES6 code today, without having to wait until the engines catch up. We'll explore source-to-source compilation, standard library polyfills, publishing modules written in ES6 to npm and the consumption of those modules by existing ES5 and new ES6 code.

**Comment by tomgco** [comment]
Awesome, I am looking forward to this one =D

**Comment by nuisanceofcats** [comment]
I've been writing ES6 in open source and corporate projects for years now and best advice I can give is:
* traceur: You're going to have a bad time interfacing with modules in other code `import { id1, id2 } from 'module'` only works with other traceur modules, not ES5 modules. The correctness of your module paths relates to how you call the API and will often be wrong. Paths within source maps are often wrong. The main project maintainer seems to deflect issues a bit too much (e.g. asking "Is this a problem" when somebody raises a blatant issue with the code).
* babel: Just go with babel rather than traceur and don't worry about the small amount of duplicated output code (babel does not use a runtime).
